name: gpcs_multitenancy_baseline_v90
label: GPCS New Multitenant Cloud Instance Configuration
description: GPCS onboarding of new cloud instance
type: panorama-gpcs
extends: skillet_panorama_v90

labels:
  service_type: gpcs
  collection: mssp

variables:
  - name: GPCS_IP
    description: Subnet infrastructure IP
    default: 192.168.250.0/24
    type_hint: ip_address
  - name: ZONE_TRUST
    description: Trust zones for GPCS
    default: trust
    type_hint: text
  - name: ZONE_UNTRUST
    description: Untrust zones for GPCS
    default: untrust
    type_hint: text


snippets:
  - name: service_connection
    xpath: /config/devices/entry[@name='localhost.localdomain']/plugins/cloud_services/service-connection
    file: service_connection.xml
  - name: gpcs_templates
    xpath: /config/devices/entry[@name='localhost.localdomain']/template
    file: gpcs_templates.xml
  - name: gpcs_template_stacks
    xpath: /config/devices/entry[@name='localhost.localdomain']/template-stack
    file: gpcs_template_stacks.xml
  - name: remote_network_devicegroup
    xpath: /config/devices/entry[@name='localhost.localdomain']/device-group
    file: gpcs_devicegroup.xml
  - name: zone
    xpath: /config/devices/entry[@name='localhost.localdomain']/template-stack/entry[@name='Remote_Network_Template_Stack']/config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/zone
    file: zone.xml
  - name: trusted_zone
    xpath: /config/devices/entry[@name='localhost.localdomain']/plugins/cloud_services/remote-networks/trusted-zones
    file: trusted_zone.xml
# gold tier security rules based on mssp gold
  - name: profile_group_unknown_url
    xpath: /config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='Remote_Network_Device_Group']/profile-group
    file: ../../internet_gateway/panorama/gold/profile_group_unknown_url.xml
  - name: tag
    xpath: /config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='Remote_Network_Device_Group']/tag
    file: ../../internet_gateway/panorama/gold/tag.xml
  - name: security_rules-security-rules-gold
    xpath: /config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='Remote_Network_Device_Group']/post-rulebase/security
    file: ../../internet_gateway/panorama/gold/security_rules_gold.xml