name: cisco
label: Cisco CPE GPCS Config
description: CPE config for Cisco
type: template
extends:

labels:
  service_type: gpcs-cpe
  collection: mssp


variables:
- name: service_ip
  description: Service IP Address obtained from gpcs service IP
  default: 192.0.9.1
  type_hint: text
- name: VPN_SHARED_KEY
  description: Preshared Key
  default: 12345678
  type_hint: text
- name: cpe_interface
  description: Interface for tunnel association
  default: GigabitEthernet1
  type_hint: text
- name: tunnel_interface
  description: Tunnel interface name
  default: Tunnel1
  type_hint: text
- name: VPN_PEER_IP
  description: Local address of the tunnel mapped to gpcs peer IP
  default: 192.0.11.1
  type_hint: text
- name: VPN_PEER_IP_netmask
  description: Network mask for tunnel interface
  default: 255.255.255.255
  type_hint: text
- name: svc_ip_netmask
  description: Netmask for match subnet
  default: 255.255.255.0
  type_hint: text

snippets:
- name: cisco_ipsec.conf
  file: cisco_ipsec.conf


